# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'protractor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 606)
        MainWindow.setMinimumSize(QtCore.QSize(857, 606))
        MainWindow.setMaximumSize(QtCore.QSize(999999, 999999))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.main_control_frame = QtWidgets.QFrame(self.frame)
        self.main_control_frame.setEnabled(False)
        self.main_control_frame.setObjectName("main_control_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_control_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.main_control_frame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.standard_select_frame = QtWidgets.QFrame(self.main_control_frame)
        self.standard_select_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.standard_select_frame.setObjectName("standard_select_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.standard_select_frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ysi_400_button = QtWidgets.QRadioButton(self.standard_select_frame)
        self.ysi_400_button.setEnabled(False)
        self.ysi_400_button.setChecked(True)
        self.ysi_400_button.setObjectName("ysi_400_button")
        self.horizontalLayout_2.addWidget(self.ysi_400_button)
        self.ysi_700_button = QtWidgets.QRadioButton(self.standard_select_frame)
        self.ysi_700_button.setObjectName("ysi_700_button")
        self.horizontalLayout_2.addWidget(self.ysi_700_button)
        self.verticalLayout_2.addWidget(self.standard_select_frame)
        self.label_2 = QtWidgets.QLabel(self.main_control_frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spinbox_resistance = QtWidgets.QSpinBox(self.main_control_frame)
        self.spinbox_resistance.setMinimum(1)
        self.spinbox_resistance.setMaximum(99999999)
        self.spinbox_resistance.setProperty("value", 5000)
        self.spinbox_resistance.setObjectName("spinbox_resistance")
        self.verticalLayout_2.addWidget(self.spinbox_resistance)
        self.label = QtWidgets.QLabel(self.main_control_frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.spinbox_degrees = QtWidgets.QSpinBox(self.main_control_frame)
        self.spinbox_degrees.setMinimum(45)
        self.spinbox_degrees.setMaximum(359)
        self.spinbox_degrees.setProperty("value", 300)
        self.spinbox_degrees.setObjectName("spinbox_degrees")
        self.verticalLayout_2.addWidget(self.spinbox_degrees)
        self.label_4 = QtWidgets.QLabel(self.main_control_frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinbox_deadzone = QtWidgets.QSpinBox(self.main_control_frame)
        self.spinbox_deadzone.setMinimum(1)
        self.spinbox_deadzone.setMaximum(40)
        self.spinbox_deadzone.setProperty("value", 10)
        self.spinbox_deadzone.setObjectName("spinbox_deadzone")
        self.horizontalLayout.addWidget(self.spinbox_deadzone)
        self.label_5 = QtWidgets.QLabel(self.main_control_frame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_8 = QtWidgets.QLabel(self.main_control_frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.line_custom_label = QtWidgets.QLineEdit(self.main_control_frame)
        self.line_custom_label.setMaxLength(64)
        self.line_custom_label.setObjectName("line_custom_label")
        self.verticalLayout_2.addWidget(self.line_custom_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.checkbox_invert = QtWidgets.QCheckBox(self.main_control_frame)
        self.checkbox_invert.setObjectName("checkbox_invert")
        self.verticalLayout_2.addWidget(self.checkbox_invert)
        self.button_generate = QtWidgets.QPushButton(self.main_control_frame)
        self.button_generate.setObjectName("button_generate")
        self.verticalLayout_2.addWidget(self.button_generate)
        self.label_3 = QtWidgets.QLabel(self.main_control_frame)
        self.label_3.setMinimumSize(QtCore.QSize(323, 31))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout_2.addWidget(self.main_control_frame, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.horizontalFrame = QtWidgets.QFrame(self.frame)
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_resist_yes = QtWidgets.QRadioButton(self.horizontalFrame)
        self.radio_resist_yes.setObjectName("radio_resist_yes")
        self.horizontalLayout_3.addWidget(self.radio_resist_yes)
        self.radio_resist_no = QtWidgets.QRadioButton(self.horizontalFrame)
        self.radio_resist_no.setObjectName("radio_resist_no")
        self.horizontalLayout_3.addWidget(self.radio_resist_no)
        self.gridLayout_2.addWidget(self.horizontalFrame, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:600;\">Steps to Calibrate:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">1. </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">Turn center potentiometer fully counter-clockwise</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">2.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Measure resistance between TP3 and TP4. This is your Resistance of Potentiometer. Save this reading for later.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">3.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Switch mode switch to 400.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">4.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Place multimeter probes in the Meter Probes slots and set to measure resistance.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">5.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Turn 2K potentiometer (RV3) until meter reads as close as possbile to 1200 ohms.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">6.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Switch mode switch to 700.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">7.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Turn 5K potentiometer (RV1) until meter reads as close as possible to 3196 ohms.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">8.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Remove meter probes. The device is now calibrated.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">9.</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"> Follow the steps to the left to generate a protractor unique to your device.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\"><br /></span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600;\">WARNING</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt;\">: This device and program are for educational purposes only. Do not calibrate active medical equipment using this device.</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Standard"))
        self.ysi_400_button.setText(_translate("MainWindow", "YSI-400"))
        self.ysi_700_button.setText(_translate("MainWindow", "YSI-700"))
        self.label_2.setText(_translate("MainWindow", "Resistance of Potentiometer (Between outer pins)"))
        self.label.setText(_translate("MainWindow", "Maximum Potentiometer Degrees (mechanical)"))
        self.label_4.setText(_translate("MainWindow", "Potentiometer \'dead-zone\' (Leave default if not sure)"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.label_8.setText(_translate("MainWindow", "Custom Label (optional)"))
        self.line_custom_label.setPlaceholderText(_translate("MainWindow", "Your name, device identifier, etc."))
        self.checkbox_invert.setText(_translate("MainWindow", "Invert Colors"))
        self.button_generate.setText(_translate("MainWindow", "Generate Protractor Image"))
        self.label_3.setText(_translate("MainWindow", "This will automatically generate a calibrated protractor\n"
"which can be printed out or saved."))
        self.label_7.setText(_translate("MainWindow", "NOT FOR MEDICAL USE"))
        self.label_17.setText(_translate("MainWindow", "Have you soldered on resistors R2 and R3?"))
        self.radio_resist_yes.setText(_translate("MainWindow", "Yes"))
        self.radio_resist_no.setText(_translate("MainWindow", "No"))
