# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'protractor_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 313)
        MainWindow.setMinimumSize(QtCore.QSize(403, 313))
        MainWindow.setMaximumSize(QtCore.QSize(403, 313))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_generate = QtWidgets.QPushButton(self.centralwidget)
        self.button_generate.setObjectName("button_generate")
        self.gridLayout.addWidget(self.button_generate, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinbox_resistance = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_resistance.setMinimum(1)
        self.spinbox_resistance.setMaximum(99999999)
        self.spinbox_resistance.setProperty("value", 1000)
        self.spinbox_resistance.setObjectName("spinbox_resistance")
        self.gridLayout_2.addWidget(self.spinbox_resistance, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinbox_deadzone = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_deadzone.setMinimum(1)
        self.spinbox_deadzone.setMaximum(40)
        self.spinbox_deadzone.setProperty("value", 10)
        self.spinbox_deadzone.setObjectName("spinbox_deadzone")
        self.horizontalLayout.addWidget(self.spinbox_deadzone)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.checkbox_invert = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_invert.setObjectName("checkbox_invert")
        self.gridLayout_2.addWidget(self.checkbox_invert, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.spinbox_degrees = QtWidgets.QSpinBox(self.centralwidget)
        self.spinbox_degrees.setMinimum(1)
        self.spinbox_degrees.setMaximum(360)
        self.spinbox_degrees.setProperty("value", 280)
        self.spinbox_degrees.setObjectName("spinbox_degrees")
        self.gridLayout_2.addWidget(self.spinbox_degrees, 3, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(323, 31))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_generate.setText(_translate("MainWindow", "Generate Protractor Image"))
        self.label_2.setText(_translate("MainWindow", "Resistance of Potentiometer (Between outer pins)"))
        self.label_5.setText(_translate("MainWindow", "%"))
        self.label_4.setText(_translate("MainWindow", "Potentiometer \'dead-zone\'. (Leave default if not sure)"))
        self.checkbox_invert.setText(_translate("MainWindow", "Invert Colors"))
        self.label.setText(_translate("MainWindow", "Maximum Potentiometer Degrees (mechanical)"))
        self.label_3.setText(_translate("MainWindow", "This will automatically generate a calibrated protractor\n"
"which can be printed out or saved."))
